[package]
name = "cmex_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
cmex_span = { path = "../cmex_span" }
cmex_ast = { path = "../cmex_ast" }
cmex_iter = { path = "../cmex_iter" }
tracing = "0.1"